### ISSUE TITLE
I don't understand how this condition can be fulfilled that I can copy several files at once, as fopen in line 22 accepts only chars and returns "-1" not finding an existing file

### ISSUE THREAD

**Issue by lubavas** [igorkagan/Igtools#1]
https://github.com/igorkagan/Igtools/blob/e863bed18645244761c70d08267afb0a503c78fd/ig_copy_file_list_to_dir.m#L34

**Comment by igorkagan** [comment]
The wildcards should be in the filelist, e.g.

file1*

file2* 

but the filelist should be existing file.
